#!/bin/bash

header="/* This is an autogenerated header file. Please use gen_images.sh */\n\n"
images=($1/*.png)
output=$2

echo -e "$header" > $output

for file in ${images[*]}
do
    name=$(basename ${file%.png})
    png2c -i $file -o - -f BGRA -p $name >> $output
done

echo "ui_image_t ui_images[] = {" >> $output
prefix=""
for file in ${images[*]}
do
    name=$(basename ${file%.png})

    if [ $file != ${images[0]} ]
    then
        prefix=","
    fi

    width=$(file $file | cut -d ' ' -f 5)
    height=$(file $file | cut -d ' ' -f 7 | sed 's/,//')
    echo -en "$prefix\n\t{ \"$name\", (EFI_GRAPHICS_OUTPUT_BLT_PIXEL *)"$name"_dat, $width, $height }" >> $output
done
echo -e "\n};" >> $output
