#!/bin/bash -e

header="/* This is an autogenerated header file. Please use gen_fonts.sh */\n\n"
images=($1/*.png)
output=$2

echo -e "$header" > $output

for file in ${images[*]}
do
    name=$(basename ${file%_font.png})
    png2c -i $file -o - -f GRAY -p "__"$name >> $output
done

echo -en "\nui_font_t ui_fonts[] = {" >> $output
prefix=""
fonts_nb=0
for file in ${images[*]}
do
    name=$(basename ${file%_font.png})

    if [ $file != ${images[0]} ]
    then
        prefix=","
    fi

    cwidth=$(echo $name | cut -d 'x' -f 1)
    cheight=$(echo $name | cut -d 'x' -f 2 | cut -d '_' -f 1)
    width=$(file $file | cut -d ' ' -f 5)
    height=$(file $file | cut -d ' ' -f 7 | sed 's/,//')
    echo -en "$prefix\n\t{ \"$name\", $width, $height, $cwidth, $cheight, __"$name"_dat }" >> $output
    fonts_nb=$((fonts_nb+1))
done
echo -e "\n};" >> $output
echo -e "UINTN ui_fonts_nb = $fonts_nb;" >> $output
